apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-product-api
  namespace: cc-demo
spec:
  selector:
    matchLabels:
      app: go-product-api
  template:
    metadata:
      labels:
        app: go-product-api
    spec:
      containers:
      - name: go-product-api
        image: <Built Container Image here>
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /data
            name: data
      imagePullSecrets: 
      - name: acr
      volumes:
        - name: data
          emptyDir: {}
            
