apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-product-api
spec:
  selector:
    matchLabels:
      app: go-product-api
  template:
    metadata:
      labels:
        app: go-product-api
    spec:
      containers:
      - name: go-product-api
        image: supadhyaya969/go-product-api:latest
        env:
        - name: OTEL_COLLECTOR_URL
          value: otel-http-service.otel.svc.cluster.local
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          emptyDir: {}
            
